# Generated by Django 3.2.13 on 2022-06-19 20:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tracking_url', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('status_mapping', models.JSONField(blank=True, default={}, null=True)),
                ('outer_script_path', models.CharField(default=None, help_text='In case of outer script needed', max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='The courier will not ba available if is_active=False')),
                ('automatic_run', models.BooleanField(default=True, help_text='To run with celery every 12 hours')),
                ('invalid_clause', models.CharField(blank=True, max_length=100, null=True)),
                ('track_details_div', models.JSONField(default=dict)),
                ('status_div', models.JSONField(default=dict)),
                ('date_time_div', models.JSONField(default=dict)),
                ('location_div', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'Courier',
            },
        ),
        migrations.CreateModel(
            name='CStatus',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'C_Status',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
        migrations.CreateModel(
            name='ZidShipGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('track_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('status_log', models.JSONField(blank=True, default={}, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.client')),
                ('courier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.courier')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.cstatus')),
            ],
            options={
                'db_table': 'Package',
                'ordering': ('-date_created',),
            },
        ),
    ]
